function Set-OutofOffice {


    [CmdletBinding()]


        param (
        
            #[Parameter(Mandatory=$true,HelpMessage='Please enter the location of the out of office message. Ex: D:\')]$CSVFileName,
            #[Parameter(Mandatory=$false)][string]$CSVPath = "\\10.210.104.55\e$\#_Posh\Info\_Data\_OutofOffice\",
            #[string]$SavePath = "\\10.210.104.55\e$\#_Posh\Info\_Results\_OutofOffice",
            [Parameter(Mandatory=$true,ValueFromPipeline=$true)][string]$Logpath,
            [Parameter(Mandatory=$true,ValueFromPipeline=$true)][string]$EmailAdd,
            [Parameter(Mandatory=$true,ValueFromPipeline=$true)][string]$InternalMsg,
            [Parameter(Mandatory=$true,ValueFromPipeline=$true)][string]$ExternalMsg     
        )

        #Variable for csv file name output
        $unqName = Get-Date -UFormat %Y%m%d_%H%M%S

        . T:\Powershell\Scripts\Gather\GetLog.ps1
             
        Try 
        {

            Write-Log "> Checking mailbox $($EmailAddress)" -ScriptName 'OutofOffice'
            
            Get-O365Mailbox -Identity $EmailAddress -ErrorAction stop
        
        } 
        Catch 
        {
            
            Write-Log ">> Error found. Check $($Logpath) for details" -ScriptName 'OutofOffice'

            Write-Warning 'Error Occurred'

            $Error > "$Logpath\Error_for_$EmailAddress.$unqName.txt"
        }
        Finally 
        {        
        
            Write-Log "> $($EmailAddress) found.`rConfiguring out of office" -ScriptName 'OutofOffice'

            #Set out of office

            Write-Log "> Setting Out of Office Message for mailbox $($EmailAddress)" -ScriptName 'OutofOffice'

            Set-O365MailboxAutoReplyConfiguration -Identity $EmailAddress -AutoReplyState Enabled -ExternalMessage $Message -InternalMessage $Message -ExternalAudience All
            
            #OPTIONS [Scheduled,Enabled,Disabled] <#-StartTime "2/22/2017 12:00:00" -EndTime "2/22/2017 17:00:00"#> -ExternalAudience All -InternalMessage $intMess -ExternalMessage $extMess 
        
            Write-Log '> Waiting to display Out of Office message' -ScriptName 'OutofOffice'
            
            Write-Log '> Getting mailbox auto reply summary' -ScriptName 'OutofOffice'

            $oooSummary = Get-O365MailboxAutoReplyConfiguration -Identity $EmailAddress

            $oooSummary | Export-Csv "T:\Powershell\Results\OutofOffice_$($EmailAddress).$unqName.csv" -NoTypeInformation -Append
             
            $oooSummaryLog = Get-O365MailboxAutoReplyConfiguration -Identity $EmailAddress| fl MailboxOwnerId, Identity, IsValid, AutoReplyState, StartTime, EndTime, ExternalAudience, InternalMessage, ExternalMessage | Out-String 
                               
        } #end if
                 
            Write-Log $oooSummaryLog -ScriptName 'OutofOffice'

            Write-Verbose "Summary for $($EmailAddress)" -Verbose

            $oooSummary                         

        
} #end function Set-OutofOffice

# Call Function

Set-OutofOffice


<# SAMPLE RUN

PS C:\Windows\system32> . H:\Powershell\Scripts\Mailbox\SetOutOfOffice.ps1

cmdlet Set-OutofOffice at command pipeline position 1
Supply values for the following parameters:
EmailAddress: IT.CollaborationApps2@IGT.com
Message: <p>{THIS IS AN AUTOMATIC REPLY GENERATED BY THE MAILBOX}<br /><br />Hello,<br /><br />Sorry this mailbox is no longer <span style="text-decoration: line-through;"><span style="text-decoration: underline;">VALID</span></span><span style="text-decoration: underline;">!</span> and therefore no reply will be sent. <br /><br />Please contact <a href="mailto:blah@blah.com">blah@blah.com</a></p><p>Regards,<br /><br />Blah</p>

Name                      Alias           Database                       ProhibitSendQuota    ExternalDirectoryObjectId
----                      -----           --------                       -----------------    -------------------------
IGT.IT_Collaboration_A... IT.Collabora... NAMPR01DG334-db132             49.5 GB (53,150,2... cb746519-6cd9-4ffb-8352-0ec8a01f1628
VERBOSE: Summary for IT.CollaborationApps2@IGT.com

RunspaceId                       : a157df72-750c-4c82-880b-bf77aba50c29
AutoDeclineFutureRequestsWhenOOF : False
AutoReplyState                   : Enabled
CreateOOFEvent                   : False
DeclineAllEventsForScheduledOOF  : False
DeclineEventsForScheduledOOF     : False
EventsToDeleteIDs                :
EndTime                          : 9/27/2019 5:00:00 PM
ExternalAudience                 : All
ExternalMessage                  : <html>
                                   <body>
                                   <p>{THIS IS AN AUTOMATIC REPLY GENERATED BY THE MAILBOX}<br>
                                   <br>
                                   Hello,<br>
                                   <br>
                                   Sorry this mailbox is no longer <span style="text-decoration:line-through"><span style="text-decoration:underline">VALID</span></span><span style="text-decoration:underline">!</span> and therefore no reply will be sent.
                                   <br>
                                   <br>
                                   Please contact <a href="mailto:blah@blah.com">blah@blah.com</a></p>
                                   <p>Regards,<br>
                                   <br>
                                   Blah</p>
                                   </body>
                                   </html>

InternalMessage                  : <html>
                                   <body>
                                   <p>{THIS IS AN AUTOMATIC REPLY GENERATED BY THE MAILBOX}<br>
                                   <br>
                                   Hello,<br>
                                   <br>
                                   Sorry this mailbox is no longer <span style="text-decoration:line-through"><span style="text-decoration:underline">VALID</span></span><span style="text-decoration:underline">!</span> and therefore no reply will be sent.
                                   <br>
                                   <br>
                                   Please contact <a href="mailto:blah@blah.com">blah@blah.com</a></p>
                                   <p>Regards,<br>
                                   <br>
                                   Blah</p>
                                   </body>
                                   </html>

DeclineMeetingMessage            :
OOFEventSubject                  :
StartTime                        : 9/26/2019 5:00:00 PM
Recipients                       :
ReminderMinutesBeforeStart       : -1
ReminderMessage                  :
MailboxOwnerId                   : IGT.IT_Collaboration_Apps_2
Identity                         : IGT.IT_Collaboration_Apps_2
IsValid                          : True
ObjectState                      : Unchanged



#>